name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: test
        uses: ./.github/myActions
      - name: echo
        run: echo "this is my action"  